## tensorflow的核心概念

Tensorflow底层最核心的概念是
- 张量：多维数据数组，即张量（tensor）
- 计算图：数据流图（data flow graphs）
- 自动微分：反向传播计算导数


### 张量数据结构

TensorFlow程序 = 张量数据结构 + 计算图算法语言

从行为特性来看，有**两种**类型的张量，
- **常量constant**：计算图中不可以被重新赋值
- **变量Variable**：被训练的参数一般被设置成变量，可以在计算图中用assign等算子重新赋值。

#### 常用的数据张量

- 向量数据：2D 张量，形状为 (samples, features)。
- 时间序列数据或序列数据：3D 张量，形状为 (samples, timesteps, features)。
- 图像：4D 张量，形状为 (samples, height, width, channels) 或 (samples, channels, height, width)。
- 视频：5D 张量，形状为 (samples, frames, height, width, channels) 或 (samples, frames, channels, height, width)。




#### 常量张量

张量的数据类型和numpy.array基本一一对应

下面来看看tensorflow中基本的数据类型


In [1]:
import numpy as np
import tensorflow as tf

# 几种常见的张量类型
i = tf.constant(1) 
l = tf.constant(1,dtype = tf.int64)
f = tf.constant(1.23)
d = tf.constant(3.14,dtype = tf.double)
s = tf.constant("hello world")
b = tf.constant(True)

# 与numpy 类型的比较
print(tf.int64 == np.int64) 
print(tf.bool == np.bool)
print(tf.double == np.float64)
print(tf.string == np.unicode) # tf.string类型和np.unicode类型不等价



True
True
True
False


##### 张量类型的关键属性

**轴的个数（阶数）** 3D 张量有 3 个轴，矩阵有 2 个轴。这在 Numpy 等 Python 库中也叫张量的 ndim ,而tensorflow称其为rank  
**形状** 这是一个整数元组，表示张量沿每个轴的维度大小（元素个数）。前面矩阵示例的形状为 (3,  5)，3D 张量示例的形状为 (3,  3,  5)   
**数据类型** 这是张量中所包含数据的类型，例如，张量的类型可以是 float32、uint8、float64 等。

In [12]:
# 标量 维度为0
scalar = tf.constant(True)
# 维度，
print(tf.rank(scalar))
print(scalar.numpy().ndim)
# 形状
print(scalar.shape)
# 数据类型
print(scalar.dtype)

# 向量 1维张量
arr =  tf.constant([1,2,3,4])
print(tf.rank(arr))
print(arr.numpy().ndim)

# 矩阵 2维张量
matrix = tf.constant([[1.0,2.0],[3.0,4.0]]) #矩阵, 2维张量
print(tf.rank(matrix))
print(matrix.numpy().ndim)

# 3D 张量，形状为 (samples, timesteps, features)。
tensor3 = tf.constant([[[1.0,2.0],[3.0,4.0]],[[5.0,6.0],[7.0,8.0]]])  
print(tensor3)
print(tensor3.shape)
print(tf.rank(tensor3))


tf.Tensor(0, shape=(), dtype=int32)
0
()
<dtype: 'bool'>
tf.Tensor(1, shape=(), dtype=int32)
1
tf.Tensor(2, shape=(), dtype=int32)
2
tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]], shape=(2, 2, 2), dtype=float32)
(2, 2, 2)
tf.Tensor(3, shape=(), dtype=int32)


##### 张量数据类型的转换

可以用tf.cast改变张量的数据类型。

可以用numpy方法将tensorflow中的张量转化成numpy中的张量。

In [15]:
#张量数据类型的转换
h = tf.constant([1,2],dtype=tf.int32)
f = tf.cast(h,tf.float32)
print(h.dtype,f.dtype)

# numpy 与 tf数据的转换

y = tf.constant([[1.0,2.0],[3.0,4.0]])
print(y.numpy()) #转换成np.array
print(y.shape)

u = tf.constant(u"你好 世界")
print(u.numpy())  
print(u.numpy().decode("utf-8"))

<dtype: 'int32'> <dtype: 'float32'>
[[1. 2.]
 [3. 4.]]
(2, 2)
b'\xe4\xbd\xa0\xe5\xa5\xbd \xe4\xb8\x96\xe7\x95\x8c'
你好 世界


#### tensflow中的变量张量(Variable)

模型中需要被训练的参数一般被设置成变量,可以在计算图中用assign等算子重新赋值。
 常量值不可以改变，常量的重新赋值相当于创造新的内存空间


In [17]:
#常量值不可以改变，常量的重新赋值相当于创造新的内存空间
c = tf.constant([1,2,3])
print(c)
print(id(c))

c = c + tf.constant([1,2,3])
print(c)
# 常量的重新赋值相当于创造新的内存空间
print(id(c))


tf.Tensor([1 2 3], shape=(3,), dtype=int32)
1540763427768
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
1541661077176


In [21]:
# 变量的值可以改变，可以通过assign, assign_add等方法给变量重新赋值
v = tf.Variable([1,2,3],name="v")
print(v)
print(id(v))
v.assign_add([1,2,3])
print(v)
print(id(v))

# 使用直接的加法仍然会改变其内存地址
# 如果想避免这个临时内存开销，我们可以使用assign_{运算符全名}函数。
v = v + tf.constant([1,2,3])
print(v)
print(id(v))




<tf.Variable 'v:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
1545864975688
<tf.Variable 'v:0' shape=(3,) dtype=int32, numpy=array([2, 4, 6])>
1545864975688
tf.Tensor([3 6 9], shape=(3,), dtype=int32)
1541656286840
