## Numpy

Python一个非常著名的第三方库，用来处理数组和矩阵的操作。

### 导入Numpy
需要使用import来导入外部的库，这里的外部是指不是python自身内置的类型。 具体的语法如下：

In [1]:
# import: 导入库
# as:将该库简写为np
# 以后调用该库的一些方法以np.xxxx
import numpy as np


### 生成Numpy数组

函数：`np.array()`  
详细的知识见官网[生成Numpy数组](https://www.numpy.org.cn/user/quickstart.html#%E6%95%B0%E7%BB%84%E5%88%9B%E5%BB%BA)


In [3]:
x = np.array([1,2,3])
print(x)
print(type(x))
print(x.dtype)

# 错误的写法
#a = np.array(1,2,3,4) 

[1 2 3]
<class 'numpy.ndarray'>
int32


### Numpy数组算术运算
数组与数组的基础运算,这里需要注意:
- 元素个数是相同
- 元素个数不同，程序就会报错
- 对应元素的乘法:也就是第一元素与第一个元素的操作
- 和单一的数值组合起来进行运算,需要在 NumPy 数组的各个元素和标量之间进行运算

具体详见官网:[算术运算](https://www.numpy.org.cn/user/quickstart.html#%E5%9F%BA%E6%9C%AC%E6%93%8D%E4%BD%9C)


In [8]:
# 创建指定类型的数的数组:flaot类型
x = np.array([1,2,3,4],dtype=float)
y = np.array([5,6,7,8],dtype=float)

print(x.dtype)

print(x+y)
print(x-y)
print(x*y)
print(x/y)
# 和单一的数值组合起来进行运算
print(x**2)
print(x/2)

float64
[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1.  4.  9. 16.]
[0.5 1.  1.5 2. ]


### Numpy的N维数组

上面我们看到生成一维数组,这里我们来看看如何生成多维数组,
- 例如 二维数组:矩阵
- 三维数组,....
可以通过一些numpy常见的函数来获得数组的信息:
- shape:数组的形状,数组的维度
- dtype:类型
- ndim:数组的轴（维度）的个数
- size:数组元素的总数
- itemsize:数组中每个元素的字节大小
- data:该缓冲区包含数组的实际元素

In [10]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.shape)
print(x.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int32
