## Numpy

Python一个非常著名的第三方库，用来处理数组和矩阵的操作。

### 导入Numpy
需要使用import来导入外部的库，这里的外部是指不是python自身内置的类型。 具体的语法如下：

In [1]:
# import: 导入库
# as:将该库简写为np
# 以后调用该库的一些方法以np.xxxx
import numpy as np


### 生成Numpy数组

函数：`np.array()`  
详细的知识见官网[生成Numpy数组](https://www.numpy.org.cn/user/quickstart.html#%E6%95%B0%E7%BB%84%E5%88%9B%E5%BB%BA)


In [3]:
x = np.array([1,2,3])
print(x)
print(type(x))
print(x.dtype)

# 错误的写法
#a = np.array(1,2,3,4) 

[1 2 3]
<class 'numpy.ndarray'>
int32


### Numpy数组算术运算
数组与数组的基础运算,这里需要注意:
- 元素个数是相同
- 元素个数不同，程序就会报错
- 对应元素的乘法:也就是第一元素与第一个元素的操作
- 和单一的数值组合起来进行运算,需要在 NumPy 数组的各个元素和标量之间进行运算

具体详见官网:[算术运算](https://www.numpy.org.cn/user/quickstart.html#%E5%9F%BA%E6%9C%AC%E6%93%8D%E4%BD%9C)


In [8]:
# 创建指定类型的数的数组:flaot类型
x = np.array([1,2,3,4],dtype=float)
y = np.array([5,6,7,8],dtype=float)

print(x.dtype)

print(x+y)
print(x-y)
print(x*y)
print(x/y)
# 和单一的数值组合起来进行运算
print(x**2)
print(x/2)

float64
[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1.  4.  9. 16.]
[0.5 1.  1.5 2. ]


### Numpy的N维数组

上面我们看到生成一维数组,这里我们来看看如何生成多维数组,
- 例如 二维数组:矩阵
- 三维数组,....
可以通过一些numpy常见的函数来获得数组的信息:
- shape:数组的形状,数组的维度
- dtype:类型
- ndim:数组的轴（维度）的个数
- size:数组元素的总数
- itemsize:数组中每个元素的字节大小
- data:该缓冲区包含数组的实际元素

Numpy数组的维度定义：
- 一维数组：向量
- 二维数组：矩阵
- 三维数组：张量tensor,多维数组


In [3]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
# 获得向量的形状
print(x.shape)
# 获得向量维度：数组的轴（维度）的个数
print(x.ndim)
# 向量数据的类型
print(x.dtype)
# 标量（单一数值）对矩阵进行算术运算
print(x*10)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32
[[10 20 30]
 [40 50 60]]


### 广播

描述了 numpy 如何在算术运算期间处理具有不同形状的数组。  
比如上面的一个例子，当一个矩阵 与一个标量进行算术运算时。  
广播的具体过程如下：
![广播的具体过程](imgs/1.jpg)

如果是一维数组与矩阵的算术运算的流程：如下
![广播的具体过程](imgs/2.jpg)

这里我们总结几条可以广播的规则：
- 数组维度不同，后缘维度的轴长相符
- 数组维度相同，其中有个轴为1

更多内容可以参考[广播](https://www.numpy.org.cn/user/basics/broadcasting.html#%E4%B8%80%E8%88%AC%E5%B9%BF%E6%92%AD%E8%A7%84%E5%88%99)

```
# 数组维度不同，后缘维度的轴长相符
Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3

# 数组维度相同，其中有个轴为1
A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5
# 数组维度相同，其中有个轴为1
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5

### 不可以的例子
A      (1d array):  3
B      (1d array):  4

A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3

```


In [5]:
# 矩阵与标量相乘
x = np.array([[1,2],[3,4]])
y = 10
print(x*y)

# 向量与矩阵相乘
x = np.array([[1,2],[3,4]])
y = np.array([10,20])
print(x*y)


[[10 20]
 [30 40]]
[[10 40]
 [30 80]]


### Numpy访问元素
元素的索引从 0 开始，利用索引访问。

更多内容可以参考[Numpy访问元素](https://www.numpy.org.cn/user/quickstart.html#%E7%B4%A2%E5%BC%95%E3%80%81%E5%88%87%E7%89%87%E5%92%8C%E8%BF%AD%E4%BB%A3)



In [9]:
x = np.array([[51, 55], [14, 19], [0, 4]])
print(x)
# 访问第0行
print(x[0])
# 访问第0行第1列
print(x[0][1])
# 利用迭代访问
for row in x:
    print(row)
   
# 拉伸为一维数组
x = x.flatten()
print(x)


[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
55
[51 55]
[14 19]
[0 4]
[51 55 14 19  0  4]


### 深度学习中常用的Numpy 函数

#### np.concatenate

>Join a sequence of arrays along an existing axis.
Parameters:	
a1, a2, … : sequence of array_like
The arrays must have the same shape, except in the dimension corresponding to axis (the first, by default).
axis : int, optional
The axis along which the arrays will be joined. If axis is None, arrays are flattened before use. Default is 0.
out : ndarray, optional
If provided, the destination to place the result. The shape must be correct, matching that of what concatenate would have returned if no out argument were specified.
Returns:	
res : ndarray
The concatenated array.

用于数组拼接

- 另外需要指定拼接的方向，默认是 axis = 0，也就是说对0轴的数组对象进行纵向的拼接（纵向的拼接沿着axis= 1方向）；
_ 拼接的数据维度是一样的

In [10]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

# axis =0 表示纵向添加
c = np.concatenate((a,b),axis=0)
print(c)
# axis =0 表示横向添加
c = np.concatenate((a,b.T),axis=1)
print(c)

# axis = None 直接拉伸为
c = np.concatenate((a,b),axis=None)
print(c)
print(c.ndim)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]
1
