In [5]:
import tensorflow as tf

print(tf.__version__)

2.3.0


MSE loss 的梯度计算

In [4]:
x = tf.random.normal([1,3])
w = tf.ones([3,2])
b =tf.ones([2])

y = tf.constant([0,1])

with tf.GradientTape() as tape:
    tape.watch([w,b])
    z = x@w+b
    logits = tf.sigmoid(z)
    loss = tf.reduce_mean(tf.losses.MSE(y,logits))

grads = tape.gradient(loss,[w,b])
print("w: ",grads[0])
print("b grad:",grads[1])

w:  tf.Tensor(
[[ 0.0678237  -0.02814421]
 [ 0.07160579 -0.02971363]
 [-0.15706988  0.06517791]], shape=(3, 2), dtype=float32)
b grad: tf.Tensor([ 0.14647852 -0.06078291], shape=(2,), dtype=float32)


In [11]:
x = tf.random.normal([4,3])
w = tf.ones([3,4])
b =tf.ones([4])
# 分成4个类型
y = tf.constant([3,1,2,0])

with tf.GradientTape() as tape:
    tape.watch([w,b])
    logits = x@w+b
    # print(logits.shape)
    y_hot = tf.one_hot(y,depth=4)
    # print(y_hot.shape)
    # 这里需要注意，在使用交叉熵的时候，要注意参数from_logits的设置
    # 因为没有做softmax这一步，也就是没有转换成概率这一步
    # 这里使用这个参数后，该函数会自动实现这个转换
    loss = tf.reduce_mean(tf.losses.categorical_crossentropy(y_hot,logits,from_logits=True))

grads = tape.gradient(loss,[w,b])
print("w: ",grads[0])
print("b grad:",grads[1])

(4, 4)
(4, 4)
w:  tf.Tensor(
[[-0.0749816  -0.14142123  0.12692438  0.08947845]
 [-0.06336007  0.26747727  0.0958017  -0.29991895]
 [ 0.07344081  0.19654597 -0.11238126 -0.15760551]], shape=(3, 4), dtype=float32)
b grad: tf.Tensor([0. 0. 0. 0.], shape=(4,), dtype=float32)
