In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.3.0


In [3]:
# 创建一个4维张量
# 可以将其认为是4张图片信息，size 32x32,通道为RGB 3 通道
x = tf.random.normal([4,32,32,3])

In [6]:
# 获取第一张图片
print(x[0])

tf.Tensor(
[[[ 1.4111199   0.16600598 -0.03780812]
  [-1.4932221  -0.41798112  0.08159686]
  [ 0.4024276   0.2250416   0.6618467 ]
  ...
  [ 0.37600568 -0.70499164 -1.2224084 ]
  [ 0.6404735   0.48435792  1.0089059 ]
  [ 0.20099573  0.2906517  -0.5051161 ]]

 [[ 1.1736503  -1.1118236   0.70008606]
  [ 0.41269335  0.30760556  0.7495875 ]
  [-0.53335994 -0.26658538  0.27211183]
  ...
  [-0.09797044 -1.3167006   0.43553832]
  [ 0.8344653  -0.8913072   1.2858182 ]
  [-1.552636    0.48604226 -0.24781388]]

 [[ 1.0503178  -1.2623255  -0.14434625]
  [-0.05450649 -0.6828267  -1.730352  ]
  [ 2.3803663  -0.23035966  1.4945626 ]
  ...
  [ 0.25526196 -0.62069243 -0.1487566 ]
  [-0.27902427  0.06555193 -1.155727  ]
  [ 1.6230292  -0.11644252 -0.5175083 ]]

 ...

 [[-0.4043723   0.7893357   0.5093014 ]
  [-0.21016851  1.0691826  -0.04391347]
  [-1.5433453   0.6810195  -0.59409875]
  ...
  [-0.9185745   0.71504015  0.01188872]
  [ 1.4612592   0.05212047  1.675374  ]
  [-2.1978424   1.7602944   0.995

In [8]:
# 取第 1 张图片的第 2 行
print(x[0][1])

tf.Tensor(
[[ 1.1736503  -1.1118236   0.70008606]
 [ 0.41269335  0.30760556  0.7495875 ]
 [-0.53335994 -0.26658538  0.27211183]
 [-2.9130888   0.43961456  1.0270851 ]
 [ 0.02771139  0.48896098 -0.6748628 ]
 [-1.1450611   0.34409884  2.0269294 ]
 [ 1.2698606  -1.5018531   0.5258715 ]
 [ 0.17759451 -0.23279259  0.2502362 ]
 [-0.4598213  -0.3278559   1.1438494 ]
 [ 1.0506855  -2.0848827   1.0645965 ]
 [ 1.2024615   1.1104017   0.66169304]
 [ 1.8086016   0.6836863   0.9973783 ]
 [-1.8029003  -0.3297337  -0.36406365]
 [-0.4732525  -0.69414824  0.5767104 ]
 [ 0.24783747 -0.93804955  0.9980065 ]
 [ 0.4445019  -0.22120537 -1.452529  ]
 [-0.3393902  -0.10324168  0.7859477 ]
 [ 0.07297668 -0.20789912 -0.8794146 ]
 [-0.08662009 -0.92738473  0.24714121]
 [-0.26247454 -0.05963833  0.55091554]
 [ 0.5385552  -0.34534863  0.44795838]
 [ 0.0328322  -0.72626215 -0.15062602]
 [-0.45322362 -1.2627798   0.9708307 ]
 [ 0.9275835   0.04559899 -2.263678  ]
 [ 0.45718     0.4912012  -0.0203399 ]
 [ 1.736112   

In [9]:
# 取第 1 张图片，第 2 行，第 3 列的数据
x[0][1][2]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.53335994, -0.26658538,  0.27211183], dtype=float32)>

In [10]:
# 取第 3 张图片，第 2 行，第 1 列的像素， B 通道(第 2 个通道)颜色强度值
x[2][1][0][1]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.11867536>

In [11]:
# 也可以直接用逗号隔开来获取
#  取第 2 张图片，第 10 行，第 3 列的数据
x[1,9,2]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.300882  ,  0.19726005,  1.5981046 ], dtype=float32)>

In [12]:
# 读取第 2,3 张图片
x[1:3]

<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 5.51905513e-01,  2.03694248e+00, -3.25668514e-01],
         [ 1.02155483e+00,  5.08638144e-01,  1.05378473e+00],
         [-4.44610536e-01, -1.06314695e+00,  1.13467298e-01],
         ...,
         [ 5.12445748e-01, -4.31703150e-01, -1.48905909e+00],
         [ 1.11862719e-01, -3.65957767e-01, -9.55177069e-01],
         [-7.39166811e-02, -8.44336033e-01,  1.10728407e+00]],

        [[ 2.13466001e+00, -7.25139022e-01,  6.23156726e-01],
         [ 6.12619340e-01, -2.69900113e-01,  6.41480982e-01],
         [ 1.51729500e+00,  3.80457580e-01, -1.04187751e+00],
         ...,
         [ 2.04889774e-01,  9.79543746e-01, -4.95744556e-01],
         [ 1.45381200e+00, -2.29961827e-01, -2.09688008e-01],
         [-1.98244110e-01, -9.53103423e-01,  1.00271833e+00]],

        [[-1.28117263e-01,  5.98450482e-01, -4.96207327e-01],
         [ 2.50426084e-01,  1.10241008e+00, -2.86755078e-02],
         [ 1.51754808e+00, -8.87751520e-01, 

In [13]:
# 读取第一张图片
x[0,::]

<tf.Tensor: shape=(32, 32, 3), dtype=float32, numpy=
array([[[ 1.4111199 ,  0.16600598, -0.03780812],
        [-1.4932221 , -0.41798112,  0.08159686],
        [ 0.4024276 ,  0.2250416 ,  0.6618467 ],
        ...,
        [ 0.37600568, -0.70499164, -1.2224084 ],
        [ 0.6404735 ,  0.48435792,  1.0089059 ],
        [ 0.20099573,  0.2906517 , -0.5051161 ]],

       [[ 1.1736503 , -1.1118236 ,  0.70008606],
        [ 0.41269335,  0.30760556,  0.7495875 ],
        [-0.53335994, -0.26658538,  0.27211183],
        ...,
        [-0.09797044, -1.3167006 ,  0.43553832],
        [ 0.8344653 , -0.8913072 ,  1.2858182 ],
        [-1.552636  ,  0.48604226, -0.24781388]],

       [[ 1.0503178 , -1.2623255 , -0.14434625],
        [-0.05450649, -0.6828267 , -1.730352  ],
        [ 2.3803663 , -0.23035966,  1.4945626 ],
        ...,
        [ 0.25526196, -0.62069243, -0.1487566 ],
        [-0.27902427,  0.06555193, -1.155727  ],
        [ 1.6230292 , -0.11644252, -0.5175083 ]],

       ...,

       

In [14]:
# 获取所有图片中前28行和28列中偶数行，列的数据
# 连续冒号中的第二间隔的数量 1表示：没有间隔，2：间隔为2，
x[:,0:28:2,0:28:2,:]

<tf.Tensor: shape=(4, 14, 14, 3), dtype=float32, numpy=
array([[[[ 1.4111199 ,  0.16600598, -0.03780812],
         [ 0.4024276 ,  0.2250416 ,  0.6618467 ],
         [-2.090089  , -0.04691235, -0.4678248 ],
         ...,
         [ 0.58827925,  0.73603576,  0.8201384 ],
         [ 0.8662613 ,  1.1725274 ,  1.0244884 ],
         [ 0.6130723 , -0.9011188 ,  0.6956503 ]],

        [[ 1.0503178 , -1.2623255 , -0.14434625],
         [ 2.3803663 , -0.23035966,  1.4945626 ],
         [ 1.2377825 , -0.69755286, -0.77585274],
         ...,
         [-1.9142946 , -1.2292606 , -0.16273005],
         [-0.9636146 ,  0.9099101 , -0.7121269 ],
         [ 1.1608808 ,  0.44661692, -0.63992643]],

        [[-0.05306759, -0.2401051 , -0.39368346],
         [-0.20637566, -0.37913522,  0.9800896 ],
         [ 0.26607746,  0.43587178, -0.8636325 ],
         ...,
         [ 0.365603  ,  0.4702165 ,  0.69236135],
         [-1.3045298 ,  0.18668155, -0.8639809 ],
         [ 0.921081  ,  1.0556195 ,  0.85552716]

In [18]:
x = tf.range(9)
print(x)
# 逆序取值，间隔为-1 表示从后往前取值
print(x[8:0:-1])
# 逆序取值的简写
print(x[::-1])
# 逆序间隔取值
print(x[::-2])

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([8 7 6 5 4 3 2 1], shape=(8,), dtype=int32)
tf.Tensor([8 7 6 5 4 3 2 1 0], shape=(9,), dtype=int32)
tf.Tensor([8 6 4 2 0], shape=(5,), dtype=int32)


In [19]:
x = tf.random.normal([4,32,32,3])
# 行、列逆序间隔采样
x[0,::-2,::-2] 

<tf.Tensor: shape=(16, 16, 3), dtype=float32, numpy=
array([[[-1.29308772e+00,  5.38005590e-01,  1.02742159e+00],
        [ 2.00242305e+00, -3.22426334e-02,  9.84386742e-01],
        [ 5.61743617e-01, -4.24915671e-01, -6.01427674e-01],
        [-2.30498815e+00, -1.14663863e+00,  3.13096195e-01],
        [-2.37346828e-01,  6.19356155e-01, -9.88838673e-01],
        [-1.43574917e+00, -3.95330824e-02, -3.19778442e-01],
        [ 6.71353161e-01, -2.00265959e-01,  7.29735494e-01],
        [ 9.14711416e-01,  2.38251519e+00,  1.37708402e+00],
        [-1.65025696e-01,  2.45161819e+00,  1.48955643e+00],
        [ 1.22146738e+00, -1.17248416e+00,  7.25129247e-01],
        [ 9.31484222e-01,  7.25929976e-01, -1.11373305e+00],
        [-1.06534755e+00,  5.21626353e-01, -1.51359069e+00],
        [-1.17013156e+00, -6.98536634e-02,  4.08745021e-01],
        [-1.45193315e+00, -1.11633015e+00, -1.91313279e+00],
        [-5.42948008e-01, -2.00611755e-01,  1.86444724e+00],
        [ 1.30856204e+00, -8.234

In [21]:
# 取某个通道的值
x[:,:,:,1]
# 读取第 1~2 张图片的 G/B 通道数据
# 高宽维度全部采集
x[0:2,...,1:]


<tf.Tensor: shape=(2, 32, 32, 2), dtype=float32, numpy=
array([[[[-1.189152  , -0.9443246 ],
         [ 0.05523964,  1.3043188 ],
         [ 0.9751051 , -1.87961   ],
         ...,
         [-0.39497155,  0.6809626 ],
         [-0.95701593,  2.2550893 ],
         [ 1.1489929 ,  0.4214332 ]],

        [[-1.2159157 , -0.53711694],
         [ 1.2600709 , -0.24245034],
         [-0.1509598 ,  0.11464472],
         ...,
         [ 0.33221862,  0.0821045 ],
         [-0.14289598,  0.243317  ],
         [-0.5287411 , -0.24355136]],

        [[-0.18738256,  1.6794236 ],
         [ 0.83954626,  0.58195704],
         [-0.48395514,  0.24363525],
         ...,
         [-0.34407416, -1.1508957 ],
         [-1.5113173 ,  0.13485673],
         [-1.2197726 ,  1.2734857 ]],

        ...,

        [[-0.32859993,  0.33254266],
         [ 0.0098058 , -2.4790065 ],
         [-1.6906353 , -0.4980218 ],
         ...,
         [ 0.7597156 , -0.15422139],
         [-1.1856453 ,  0.54915154],
         [ 1.3006

In [22]:
# 读取 R/G 通道数据
# 所有样本，所有高、宽的前 2 个通道
# 用省略号表示前面的数据通道所有样本，这样避免写那么多冒号
# x[:,:,:,:2]
x[...,:2]

<tf.Tensor: shape=(4, 32, 32, 2), dtype=float32, numpy=
array([[[[ 0.4504957 , -1.189152  ],
         [-1.2702811 ,  0.05523964],
         [ 0.3881399 ,  0.9751051 ],
         ...,
         [-1.3132106 , -0.39497155],
         [-1.3109196 , -0.95701593],
         [-2.0407763 ,  1.1489929 ]],

        [[-0.93237543, -1.2159157 ],
         [ 0.14854506,  1.2600709 ],
         [-0.4672979 , -0.1509598 ],
         ...,
         [-0.5474464 ,  0.33221862],
         [-0.42066896, -0.14289598],
         [ 2.0871544 , -0.5287411 ]],

        [[ 0.4774513 , -0.18738256],
         [-0.17364183,  0.83954626],
         [-0.1508127 , -0.48395514],
         ...,
         [ 0.89736706, -0.34407416],
         [ 1.3193246 , -1.5113173 ],
         [-0.79845977, -1.2197726 ]],

        ...,

        [[-0.08771281, -0.32859993],
         [ 0.6256346 ,  0.0098058 ],
         [-0.65916574, -1.6906353 ],
         ...,
         [ 1.2809856 ,  0.7597156 ],
         [-1.9192423 , -1.1856453 ],
         [ 0.8062

### tf.gather

从params的axis维根据indices的参数值获取切片,适合抽取不连续区域的子集.



In [32]:
# tf.gather
# data: [classes, students, subjects]
a = tf.random.normal([4,35,8])
# 获取第2，3个班级的数据
print(tf.gather(a,axis=0,indices=[2,3]).shape)
# 该索引下的数据
print(tf.gather(a,axis=0,indices=[2,1,3,0]).shape)

# 获取4个班级中，第2,3,7,9,11学生的成绩
print(tf.gather(a,axis=1,indices=[2,3,7,9,11]).shape)

# 获取4个班级中，所有学生中第3，5，7,工3门课的成绩
print(tf.gather(a,axis=2,indices=[3,5,7]).shape)


(2, 35, 8)
(4, 35, 8)
(4, 5, 8)
(4, 35, 3)
