In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.3.0


维度变换相关函数主要有 tf.reshape, tf.squeeze, tf.expand_dims, tf.transpose.

tf.reshape 可以改变张量的形状。

tf.squeeze 可以减少维度。

tf.expand_dims 可以增加维度。

tf.transpose 可以交换维度。

通过 tf.reshape(x, new_shape)，可以将张量的视图任意地合法改变，但是其本质上不会改变张量元素的存储顺序，所以，该操作实际上非常迅速，并且是可逆的。

In [3]:
a = tf.random.uniform(shape=[1,3,3,2],minval=0,maxval=255,dtype=tf.int32)

print(a.shape,a.ndim,"\n",a)

(1, 3, 3, 2) 4 
 tf.Tensor(
[[[[167 112]
   [  1 142]
   [252  30]]

  [[ 77  11]
   [ 79 181]
   [ 78 142]]

  [[ 26 218]
   [121 146]
   [ 75 108]]]], shape=(1, 3, 3, 2), dtype=int32)


In [4]:
# 改成 （2,9）形状的张量
b = tf.reshape(a,shape=[2,9])
print(b.shape,"\n",b)

(2, 9) 
 tf.Tensor(
[[167 112   1 142 252  30  77  11  79]
 [181  78 142  26 218 121 146  75 108]], shape=(2, 9), dtype=int32)


In [6]:
# 改回到原来的shape,里面的元素并没有变化
c =tf.reshape(b,shape=[1,3,3,2])
print(c.shape,"\n",c)

(1, 3, 3, 2) 
 tf.Tensor(
[[[[167 112]
   [  1 142]
   [252  30]]

  [[ 77  11]
   [ 79 181]
   [ 78 142]]

  [[ 26 218]
   [121 146]
   [ 75 108]]]], shape=(1, 3, 3, 2), dtype=int32)


In [7]:
# 使用-1 表示该维度大小可以根据实际情况计算
d = tf.reshape(a,[-1,2,3])
print(d.shape,"\n",d)

(3, 2, 3) 
 tf.Tensor(
[[[167 112   1]
  [142 252  30]]

 [[ 77  11  79]
  [181  78 142]]

 [[ 26 218 121]
  [146  75 108]]], shape=(3, 2, 3), dtype=int32)


如果张量在某个维度上只有一个元素，利用tf.squeeze可以消除这个维度。

和tf.reshape相似，它本质上不会改变张量元素的存储顺序。

张量的各个元素在内存中是线性存储的，其一般规律是，同一层级中的相邻元素的物理地址也相邻。

In [8]:
# 将所有为维度为1的删除
s = tf.squeeze(a)
print(s.shape,"\n",s)

(3, 3, 2) 
 tf.Tensor(
[[[167 112]
  [  1 142]
  [252  30]]

 [[ 77  11]
  [ 79 181]
  [ 78 142]]

 [[ 26 218]
  [121 146]
  [ 75 108]]], shape=(3, 3, 2), dtype=int32)


In [9]:
# 指定需要删除的维度位置
s2 = tf.squeeze(a,axis=0)
print(s2.shape,"\n",s2)

(3, 3, 2) 
 tf.Tensor(
[[[167 112]
  [  1 142]
  [252  30]]

 [[ 77  11]
  [ 79 181]
  [ 78 142]]

 [[ 26 218]
  [121 146]
  [ 75 108]]], shape=(3, 3, 2), dtype=int32)


In [10]:
# #在第0维插入长度为1的一个维度
d = tf.expand_dims(s,axis=0)
print(d.shape,"\n",d)

(1, 3, 3, 2) 
 tf.Tensor(
[[[[167 112]
   [  1 142]
   [252  30]]

  [[ 77  11]
   [ 79 181]
   [ 78 142]]

  [[ 26 218]
   [121 146]
   [ 75 108]]]], shape=(1, 3, 3, 2), dtype=int32)


交换维度位置
tf.transpose可以交换张量的维度，与tf.reshape不同，它会改变张量元素的存储顺序。

tf.transpose常用于图片存储格式的变换上。

In [11]:
x = tf.random.normal([2,32,32,3])

y = tf.transpose(x,perm=[0,3,1,2])

print(y.shape)

(2, 3, 32, 32)


复制数据
tf.tile


In [12]:
b = tf.constant([1,2])
# 插入一个新的维度
t = tf.expand_dims(b,axis=0)
print(t)


tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)


In [14]:
# 样本复制一份
b = tf.tile(t,multiples=[2,1])
print(b)

tf.Tensor(
[[1 2]
 [1 2]], shape=(2, 2), dtype=int32)


In [17]:
x = tf.range(4)
x = tf.reshape(x,shape=[2,2])
print(x)

tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32)


In [18]:
# 列方向复制
x = tf.tile(x,multiples=[1,2])
print(x)

tf.Tensor(
[[0 1 0 1]
 [2 3 2 3]], shape=(2, 4), dtype=int32)


In [20]:
# 行方向进行复制3份
x = tf.tile(x,multiples=[3,1])
print(x)

tf.Tensor(
[[0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]], shape=(12, 4), dtype=int32)
