## 数学运算


加、减、乘、除运算

In [1]:
import tensorflow as tf
import numpy as np

a = tf.range(5)
b = tf.constant(2)

# 相加
print(a+b)
# 相减
print(a-b)
# 相乘
print(a*b)
# 相除
print(a/b)
# 整除
print(a//b)
# 取余
print(a%b)


tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)
tf.Tensor([-2 -1  0  1  2], shape=(5,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
tf.Tensor([0.  0.5 1.  1.5 2. ], shape=(5,), dtype=float64)
tf.Tensor([0 0 1 1 2], shape=(5,), dtype=int32)
tf.Tensor([0 1 0 1 0], shape=(5,), dtype=int32)


乘方，开方，指数，对数运算
- tf.pow  乘方
- tf.square 平方
- tf.sqrt 开平方
- tf.exp 指数
- tf.math.log 对数, 其底为e,

In [3]:
x = tf.constant([1.,2.,3.])
# 平方运算
print(x**2)
print(tf.pow(x,2))
print(tf.square(x))

tf.Tensor([1. 4. 9.], shape=(3,), dtype=float32)
tf.Tensor([1. 4. 9.], shape=(3,), dtype=float32)
tf.Tensor([1. 4. 9.], shape=(3,), dtype=float32)


In [5]:
# 开平方
print(x**0.5)
print(tf.sqrt((x)))

tf.Tensor([1.        1.4142135 1.7320508], shape=(3,), dtype=float32)
tf.Tensor([1.        1.4142135 1.7320508], shape=(3,), dtype=float32)


In [7]:
# 指数
print(2**x) # 2 为底的指数
print(tf.exp(x)) # e 为底的指数

tf.Tensor([2. 4. 8.], shape=(3,), dtype=float32)
tf.Tensor([ 2.7182817  7.389056  20.085537 ], shape=(3,), dtype=float32)


In [14]:
x = tf.exp(3.)
# 其底为e
print(tf.math.log(x))

# 如何变成10或者2
x = tf.constant(100.)
print(tf.math.log(x))
# 以10为底
print(tf.math.log(x)/tf.math.log(10.))
# 以2为底
print(tf.math.log(x)/tf.math.log(2.))

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(4.6051702, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(6.643856, shape=(), dtype=float32)


## 矩阵运算

矩阵乘法:
- `@
- tf.mulmat


In [16]:
a = tf.random.normal([4,3,28,32])
b = tf.random.normal([4,3,32,2])

print((a@b).shape)

(4, 3, 28, 2)


In [17]:
a = tf.random.normal([4,28,32])
b = tf.random.normal([32,16])

# 先自动扩展在相乘
print(tf.matmul(a,b).shape)

(4, 28, 16)
