## 分割与合并

- tf.concat
- tf.split
- tf.stack
- tf.unstack

### tensor的拼接
 
 tf.concat([...],axis,name)

> Args:
  - values: A list of Tensor objects or a single Tensor.
  - axis: 0-D int32 Tensor. Dimension along which to concatenate. Must be
    in the range [-rank(values), rank(values)). As in Python, indexing for axis is 0-based. Positive axis in the rage of [0, rank(values)) refers to axis-th dimension. And negative axis refers to axis + rank(values)-th dimension.
  - name: A name for the operation (optional).

在使用该函数的时候，不会改变tensor的维度大小，注意一点就是需要合并的方向的维度大小可以不同，但是其他的维度大小必须一致，不然就会无法合并
Dim = d

In [1]:
import tensorflow as tf
import numpy as np
#  [class1-4, students, scores]
a = tf.random.uniform([4,35,8],0,100,tf.int32)
#  [class5-6, students, scores]
b = tf.random.uniform([2,35,8],0,100,tf.int32)

In [7]:
# 需要实现两个班级的数据的融合
c = tf.concat([a,b],axis=0)
print(c.shape)
# 会报错，维度大小不匹配
# d = tf.concat([a,b],axis=1)
# print(c.shape)

(6, 35, 8)


In [9]:
a = tf.ones([2,3])
b = tf.ones([4,3])

c = tf.concat([a,b],axis=0)
print(c.shape)

(6, 3)


### stack 与 unstack 堆叠
堆叠在一起，会改变维度的数量,
所有的维度尺寸都要一致。它需要所有待合并的张量 shape 完全一致才可
合并

In [7]:
#  [class1-4, students, scores]
a = tf.random.uniform([4,35,8],0,100,tf.int32)
#  [class5-6, students, scores]
b = tf.random.uniform([4,35,8],0,100,tf.int32)

c =tf.concat([a,b],axis = 0)

# 会增加一个指定的维度，然后存放数据
d = tf.stack([a,b],axis = 0)
print(c.shape)
print(d.shape)

e = tf.stack([a,b],axis=3)
print(e.shape)

f = tf.stack([a,b],axis=2)
print(f.shape)

(8, 35, 8)
(2, 4, 35, 8)
(4, 35, 8, 2)
(4, 35, 2, 8)


In [17]:
a = tf.range(12)
a = tf.reshape(a,[3,4])
print(a)
b = tf.range(24,delta=2)
b =tf.reshape(b,[3,4])
print(b)

c = tf.stack([a,b],axis=0)
print(c)

aa,bb = tf.unstack(c,axis=0)
print(aa,bb)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32) tf.Tensor(
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]], shape=(3, 4), dtype=int32)


### split

tf.split是tf.concat的逆运算，可以指定分割份数平均分割，也可以通过指定每份的记录数量进行分割。

> 参数：
- x：待分割张量
- num_or_size_splits: 切割方案，当为单个值的时候，表示切割的份数，当为list的时候[2,2,3]，表示每份的长度为2，2，3
- axis:表示分割的维度索引号

In [18]:
tf.split(c,num_or_size_splits= 2,axis=0)

[<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])>, <tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
 array([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]]])>]

In [20]:
a = tf.range(24)
a = tf.reshape(a,[6,4])
print(a)
# 指定分割的份数
tf.split(a,[1,2,3],axis=0)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]], shape=(6, 4), dtype=int32)


[<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[0, 1, 2, 3]])>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])>,
 <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])>]