## 张量常用的数据统计

比如统计最值，最值的位置，均值，范数等信息。

### 向量范数
向量范数(Vector Norm)表征向量"长度"的一种度量方法。常见的范数有：L1,L2,无穷大范数：例如向量的范数定义
- L1 范数：向量所有元素的绝对值之和
- L2 范数：向量所有元素的平方和，在开根号
- inf 范数：向量所以元素绝对值的最大值

利用tf.norm(x,ord)来求解：
- ord =1 ：表示L1
- ord = 2: L2 
- ord = np.inf 表示最大值

In [10]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.3.0


In [6]:
x = tf.ones([2,2])
print(tf.norm(x,ord=1))
print(tf.norm(x,ord=2))
print(tf.norm(x,ord=np.inf))

tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


In [12]:
#指定轴上范数
x = tf.ones([2,3])
# 行的方向
print(tf.norm(x,ord=1,axis=0))
print(tf.norm(x,ord=2,axis=0))
# 列的方向
print(tf.norm(x,ord=2,axis=1))

tf.Tensor([2. 2. 2.], shape=(3,), dtype=float32)
tf.Tensor([1.4142135 1.4142135 1.4142135], shape=(3,), dtype=float32)
tf.Tensor([1.7320508 1.7320508], shape=(2,), dtype=float32)


### 查找最值，均值，和以及最值的索引号
- tf.reduce_max
- tf.reduce_min
- tf.reduce_mean
- tf.reduce_sum
- tf.argmax
- tf.argmin

>参数：
- 第一个参数input_tensor： 输入的待降维的tensor;
- 第二个参数axis： 指定的轴方向，如果不指定，则计算所有元素;
- 第三个参数keep_dims：是否降维度，设置为True，输出的结果保持输入tensor的形状，设置为False，输出结果会降低维度;


例如 shape[4,10], 记录的时候样本个数为4，10个类别的概率，需要找出每个样本的最大概率的值。

In [19]:
x = tf.random.uniform(shape=[4,10],minval=0,maxval=1,dtype=tf.float32)
# 关于指定轴的理解：这里要求每一行中列元素的最大值，所以设置为列的方向
print(tf.reduce_max(x,axis=1))
print(tf.reduce_min(x,axis=1))
print(tf.reduce_mean(x,axis=1))
print(tf.reduce_sum(x,axis=1))

tf.Tensor([0.90580153 0.935712   0.9590367  0.94939566], shape=(4,), dtype=float32)
tf.Tensor([0.12353003 0.06850481 0.03555584 0.26242328], shape=(4,), dtype=float32)
tf.Tensor([0.5966229 0.5580625 0.508815  0.4725522], shape=(4,), dtype=float32)
tf.Tensor([5.966229 5.580625 5.08815  4.725522], shape=(4,), dtype=float32)


In [20]:
# 不指定轴，则计算所有的元素的最值
x = tf.random.uniform(shape=[4,10],minval=0,maxval=1,dtype=tf.float32)
tf.reduce_max(x),tf.reduce_min(x),tf.reduce_mean(x),tf.reduce_sum(x)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.99992895>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.020911574>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.5184097>,
 <tf.Tensor: shape=(), dtype=float32, numpy=20.73639>)

一个实际 的案例

In [26]:
out = tf.random.normal([4,10])
y = tf.constant([1,2,2,0])
y = tf.one_hot(y,depth=10)
# 计算每个样本的误差：均方差
loss = tf.keras.losses.mse(y,out)
mse = tf.reduce_mean(tf.square(out-y),axis=1)
print(mse)
print("样本误差：",loss)
# 计算总的评价误差
loss = tf.reduce_mean(loss)
print("总的均值误差：",loss)

tf.Tensor([2.7964349 0.8372906 1.47877   1.5083137], shape=(4,), dtype=float32)
样本误差： tf.Tensor([2.7964349 0.8372906 1.47877   1.5083137], shape=(4,), dtype=float32)
总的均值误差： tf.Tensor(1.6552023, shape=(), dtype=float32)
