## 张量的填充与复制

在保持原有的数据的情况下，对张量进行填充，一般填充0，可以沿着指定轴的方向进行填充。
tf.pad(tensor, paddings, mode='CONSTANT', constant_values=0, name=None)

>Args: 
- tensor: A Tensor. 
- paddings: A Tensor of type int32.
- mode: One of "CONSTANT", "REFLECT", or "SYMMETRIC" (case-insensitive) - constant_values: In "CONSTANT" mode, the scalar pad value to use. Must be same type as tensor. 
- name: A name for the operation (optional).

第二个参数padding尤其重要，一般有几个维度就会有几个[0,0]

In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.3.0


In [2]:
a = tf.reshape(tf.range(9),[3,3])
print(a)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [3]:
b = tf.pad(a,[[0,0],[0,0]])
print(b)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [5]:
# 第一个轴的上面，填充1行
b = tf.pad(a,[[1,0],[0,0]])
print(b)

tf.Tensor(
[[0 0 0]
 [0 1 2]
 [3 4 5]
 [6 7 8]], shape=(4, 3), dtype=int32)


In [8]:
# 上下给添加一行，左右个添加两列
b = tf.pad(a,[[1,1],[2,2]])
print(b)

tf.Tensor(
[[0 0 0 0 0 0 0]
 [0 0 0 1 2 0 0]
 [0 0 3 4 5 0 0]
 [0 0 6 7 8 0 0]
 [0 0 0 0 0 0 0]], shape=(5, 7), dtype=int32)


### 复制

tf.tile (input, multiples, name=None)
 沿着指定的维度进行复制

 >Args: 
 - input: A Tensor. 1-D or higher. 
 - multiples: A Tensor. Must be one of the following 
 - types: int32, int64. 1-D. Length must be the same as the number of dimensions in input 
 - name: A name for the operation (optional).



In [10]:
# [1,2],表示第一个维度复制1，就表示不复制，
# 第二个维度复制2份
b = tf.tile(a,[1,2])
print(b)

tf.Tensor(
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]], shape=(3, 6), dtype=int32)


In [11]:
b = tf.tile(a,[2,1])
print(b)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]], shape=(6, 3), dtype=int32)


In [12]:
b  =tf.tile(a,[2,2])
print(b)

tf.Tensor(
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]], shape=(6, 6), dtype=int32)
