In [2]:
import tensorflow as tf

# 机器的CPU的数量
physical_devices = tf.config.experimental.list_physical_devices('CPU')
print(len(physical_devices))
print(physical_devices)
# 机器的GPU的数量
physical_devices = tf.config.experimental.list_physical_devices('GPU')
print(len(physical_devices))
print(physical_devices)

1
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
0
[]


## 张量

张量是tensorflow中最基本的类型，是操作的数据流。先来看看如何在tensoflow中表示：不同维度的张量创建
- 标量：scalar
		1.1
		tf.constant(1.2)
- 向量：vector
		[1.1,2.2]
		tf.constant([1.1,2.2])
- 矩阵：matrix
		[[1.1,2.2],[3.3,4.4]]
		tf.constant([[1.1,2.2],[3.3,4.4]])
- 三维张量


In [3]:
# 标量的创建
a = 1.1 
a_tf = tf.constant(1.1)
# 查看类型以及判断张量类型
print(type(a),type(a_tf),tf.is_tensor(a_tf))

<class 'float'> <class 'tensorflow.python.framework.ops.EagerTensor'> True


In [8]:
# 向量
b = [1.1,2.2]
b_tf = tf.constant([1.1,2.2])
# 张量相关的信息
b_tf

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.1, 2.2], dtype=float32)>

上面可以看出张量里面还是包含着一些属性:
- shape
- dtype
- numpy
等等

In [9]:
# 张量转换成numpy也是非常简单
b_tf.numpy()

array([1.1, 2.2], dtype=float32)

In [11]:
#创建矩阵
c = tf.constant([[1,2],[3,4]])
c,c.shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>, TensorShape([2, 2]))

In [13]:
# 创建三维张量
d = tf.constant([[[1,2],[3,4]],[[1,2],[3,4]]])
d,d.shape

(<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[1, 2],
         [3, 4]]])>, TensorShape([2, 2, 2]))

### 张量的类型

- int, float,double
- bool
- string



#### 数值类型

创建张量时可以指定数值类型，包括数值的长度

In [15]:
# 数值类型选用不同的空间大小会影响结果
print(tf.constant(123456789,dtype=tf.int16))
print(tf.constant(123456789,dtype=tf.int32))

tf.Tensor(-13035, shape=(), dtype=int16)
tf.Tensor(123456789, shape=(), dtype=int32)


In [17]:
# 数值类型选用不同的空间大小会影响结果
import numpy as np
print(np.pi)
print("tf.float16: ",tf.constant(np.pi,dtype=tf.float16))
print("tf.float32: ",tf.constant(np.pi,dtype=tf.float32))
print("tf.float64: ",tf.constant(np.pi,dtype=tf.float64))
print("tf.double: ",tf.constant(np.pi,dtype=tf.double))

3.141592653589793
tf.float16:  tf.Tensor(3.14, shape=(), dtype=float16)
tf.float32:  tf.Tensor(3.1415927, shape=(), dtype=float32)
tf.float64:  tf.Tensor(3.141592653589793, shape=(), dtype=float64)
tf.double:  tf.Tensor(3.141592653589793, shape=(), dtype=float64)


通过访问张量的 dtype 成员属性可以判断张量的保存精度

In [18]:
a = tf.constant(np.pi,dtype=tf.float16)
print('before: ',a.dtype)
# 如果精度不符合要求，则进行转换
if a.dtype != tf.float32:
    # tf.cast 函数可以完成类型转换
    a = tf.cast(a,tf.float32)
print("after: ",a.dtype)

before:  <dtype: 'float16'>
after:  <dtype: 'float32'>



#### 字符串类型

通过传入字符串对象即可创建字符串类型的张量，在 tf.strings 模块中，提供了常见的字符串类型的工具函数，如小写化 lower()、 拼接 join()、 长度 length()、 切分 split()等。

In [16]:
a= tf.constant("Hello TF2.x")
print(a)
# 小写变换
print(tf.strings.lower(a))

tf.Tensor(b'Hello TF2.x', shape=(), dtype=string)
tf.Tensor(b'hello tf2.x', shape=(), dtype=string)


#### 布尔类型
布尔类型的张量只需要传入 Python 语言的布尔类型数据，转换成 TensorFlow 内部布尔型即可。


In [11]:
a = tf.constant(True)
print(a,a.dtype)
# 创建布尔类型的向量
b = tf.constant([True,False])
print(b,b.shape)

tf.Tensor(True, shape=(), dtype=bool) <dtype: 'bool'>
tf.Tensor([ True False], shape=(2,), dtype=bool) (2,)


TensorFlow 的布尔类型和 Python 语言的布尔类型并不等价，不能通用

In [13]:
a = tf.constant(True)
# TF 布尔类型张量与 python 布尔类型比较
print(a is True)
# 但是数值可以用来比较
print(a == True)

False
tf.Tensor(True, shape=(), dtype=bool)


### 类型转换

#### 与numpy的相互转换

这里插一个点到时关于张量创建的时候也会提到，就是与numpy的相互转换

In [22]:
a = np.arange(5)
print(a,a.dtype)

# numpy to tensor
aa = tf.convert_to_tensor(a)
print(aa)
# 转换的时候可以指定数据的类型
aa = tf.convert_to_tensor(a,dtype=tf.int64)
print(aa)

# tensor to numpy
a = tf.constant(12.3,dtype=tf.float16)
print(a)
aa = a.numpy()
print(aa,aa.dtype)

[0 1 2 3 4] int32
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor(12.3, shape=(), dtype=float16)
12.3 float16
