# 创建张量

## from numpy,list

上一个小节介绍了这种方法，tf.conver_to_tensor函数来创建新的tensor，可以将numpy与list等对象转换成Tensor 类型。

In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.3.0


In [5]:
a = [1,2,3]
aa = tf.convert_to_tensor(a)
print(aa)

b = np.array([[1,2,3],[4,5,6]])
bb  = tf.convert_to_tensor(b)
print(bb)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


## 创建全0或全1张量

通过控制 shape来获得不同的形状的数据类型。
- tf.zeros
- tf.ones

In [2]:
# 创建一个标量
print(tf.zeros([]),tf.ones([]))
# 创建一个向量
print(tf.zeros([2]),tf.ones([3]))
# 创建一个矩阵
print(tf.zeros([2,4]),tf.ones([3,5]))

tf.Tensor(0.0, shape=(), dtype=float32) tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor([0. 0.], shape=(2,), dtype=float32) tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float32) tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(3, 5), dtype=float32)


- tf.zeros_like
- tf.ones_like

> Args:
  - input: A `Tensor`.
  - dtype: A type for the returned `Tensor`. Must be `float16`, `float32`,
    `float64`, `int8`, `uint8`, `int16`, `uint16`, `int32`, `int64`,
    `complex64`, `complex128`, `bool` or `string`.
  - name: A name for the operation (optional).

也可以通过使用zeros_like,ones_like 来创建一个与某个张量shape一致的，且内容为全 0 或全 1 的张量。


In [11]:
a = tf.constant([[1,2],[3,4]])
print(a)
b = tf.ones_like(a)
print(b)
c = tf.zeros_like(a)
print(c)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int32)


## 创建自定义数值的张量
上面我们看到的是，只能创建0，1等类型的张量，如果我们想创建任意数值的张量呢？
通过 tf.fill(shape, value)可以创建全为自定义数值 value 的张量，形状由 shape 参数指定。

>Args:
  - dims: A 1-D sequence of non-negative numbers. Represents the shape of the
    output `tf.Tensor`. Entries should be of type: `int32`, `int64`.
  - value: A value to fill the returned `tf.Tensor`.
  - name: Optional string. The name of the output `tf.Tensor`.


In [16]:
# 创建标量
print(tf.fill([],2))
# 创建向量
print(tf.fill([2],-1))
# 创建矩阵
print(tf.fill([3,3],5))

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([-1 -1], shape=(2,), dtype=int32)
tf.Tensor(
[[5 5 5]
 [5 5 5]
 [5 5 5]], shape=(3, 3), dtype=int32)


## 创建各种(正态,均匀)分布的张量

可以通过tf.random.normal(shape, mean=0, stddev=1, dtype=dtypes.float32, seed=None, name=None)



In [38]:
# 标准正太分布
print(tf.random.normal([3,3]))
# 创建均值为1，标准差为2d的正太分布
print(tf.random.normal([2,2],mean=1,stddev=2))

tf.Tensor(
[[-0.62201107  0.2999319  -0.5537199 ]
 [-0.58671755  0.6487386  -0.54981697]
 [ 0.16537268 -1.2368505  -0.48971233]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 1.3149339 -3.1893334]
 [ 0.7455982 -0.5621269]], shape=(2, 2), dtype=float32)


创建均值分布的张量

uniform: (shape, minval=0, maxval=None, dtype=dtypes.float32, seed=None, name=None)



In [40]:
# 创建采样自[0,1)均匀分布的矩阵
print(tf.random.uniform([3,3]))
print(tf.random.uniform([2,2],maxval=10))


tf.Tensor(
[[0.33640003 0.23915172 0.3456241 ]
 [0.06558251 0.5055071  0.7238368 ]
 [0.87329626 0.53964984 0.5348885 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[4.099859  5.5402937]
 [5.5692935 9.2914095]], shape=(2, 2), dtype=float32)
