## 多维数组的运算

为了后面能够顺利实现神经网络的高效运算，这里要先了解一下多维数组的一些基本概念和运算。

### 多维数组
多维指的是一个数据需要表示的维度。
一维数组：向量，一条线性，
二维数组：矩阵，一个平面
三维数组：立体，一个立体

### 一维数组
在Numpy中，可以使用如下函数来获得对数组数据的信息：
- dtype:类型
- ndim:数组的轴（维度）的个数,返回的是一个元组
- size:数组元素的总数
- itemsize:数组中每个元素的字节大小
- data:该缓冲区包含数组的实际元素


In [7]:
import numpy as np
# 只有一个中括号
x = np.array([1,2,3])
print(x)
# 数组的维度
print(np.ndim(x))
print(x.ndim)
# 数组的形状
print(x.shape)
# 数组的数据类型
print(x.dtype)

[1 2 3]
1
1
(3,)
int32


### 二维数组

Numpy二维数组的数据组成的形式，是有两个中括号。
- ndim 维度为2
- 数据是由排和列组成的矩阵
- shape(2,3),表示行数为2，列数为3.
    - shape[0] :表示行数
    - shape[1]:表示列数

In [8]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
# 数组的维度
print(x.ndim)
# 数组的形状
print(x.shape)
# 数组的数据类型
print(x.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int32


#### 矩阵的乘法

Numpy中的矩阵的乘法是利用如下的函数：
- `np.dot(A,B)`
- 矩阵的乘积也称为点积

矩阵乘法的工作原理：
- 矩阵的乘积是通过左边矩阵的行（横向）和右边矩阵的列（纵向）以对应元素的方式相乘后再求和而得到的
- 运算的结果保存为新的多维数组的元素
    - 矩阵A的第1行与矩阵B的第1列乘积的结果，就放到新矩阵的第1行和第1列
    - 左边的矩阵决定结果的行号，右边的矩阵决定结果的列号
    
具体coding如下

In [3]:
import numpy as np
# 矩阵的乘法
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
print(A.shape)
print(B.shape)
C = np.dot(A,B)
print(C)
print(C.shape)

# 二维矩阵与一维矩阵的乘法
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([7,8])

print(A.shape)
print(B.shape)

C = np.dot(A,B)
print(C)

(2, 3)
(3, 2)
[[22 28]
 [49 64]]
(2, 2)
(3, 2)
(2,)
[23 53 83]


不是任何矩阵都可以做乘法的，一条基本的原则是：
- 矩阵的第 1 维和矩阵的第 0 维的元素个数一致得到新的矩阵shape(A.shape[0],B.shape[1])

![矩阵乘法的原则](imgs/8.jpg)

#### 神经网络的内积

上面我们一起看了多维矩阵的内积的运算，其实我们我们实现的神经网络也就是这样一个过程。我们先来复习一下，之前是如何来计算神经网络的。

以前我们只有一层而且神经元的个数也只有一个，所以用简单的矩阵乘法和调用了Nunpy中的sum函数来实现。其实这里也可以用矩阵的内积来实现。
- w 需要转置成二维向量
- 使用内积。

```
x = np.array([x1,x2])
w = np.array([0.5,0.5])
b = -0.6
    
result = np.sum(x*w)+b

```


In [6]:
# 感知机的矩阵内积实现

def AND(x1,x2):
    x = np.array([x1,x2])
    # 这里w 需要改成二维的向量
    w = np.array([[0.5],[0.5]])
    b = -0.6
    # 利用矩阵内积
    result = np.dot(x,w)+b
    
    if result >0:
        return 1
    else:
        return 0  
    
print(AND(0,1))
print(AND(1,1))

0
1


这里我们再来看看神经网络的层的实现例子。与感知机相比，更加复杂。具体如下图的示例：
![](imgs/9.jpg)

x:[x1,x2]是一个一维数组
w:[[w11,w21,w31]
   [w12,w22,w32]]是一个矩阵
   
这样使用点积很方便就实现了对于Y的计算。具体如下coding:

In [7]:
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])

print(X.shape)
print(W.shape)

Y = np.dot(X,W)
print(Y)
print(Y.shape)

(2,)
(2, 3)
[ 5 11 17]
(3,)
